### ISSUE TITLE
[meta] Publish Candidate Recommendation

### ISSUE THREAD

**Issue by anssiko** [w3c/remote-playback#73]
This meta issue tracks progress toward the [Remote Playback API][1] Candidate Recommendation (CR) publication. Editor: @mounirlamouri

By publishing a CR we:

* ask the entire W3C membership to provide feedback,
* formally collect implementation experience to demonstrate that the specification works in practice.

The [CR requirements][2] are the following from the W3C Process perspective:

* [x] must show that the specification has met all Working Group requirements, or explain why the requirements have changed or been deferred,
  * meets requirements

* [x] must document changes to dependencies during the development of the specification,
  * new normative reference since FPWD: [MIXED-CONTENT] CR
* [x] must document how adequate implementation experience will be demonstrated,
  * [x] test plan / test suite
    * https://github.com/w3c/web-platform-tests/tree/master/remote-playback
      * [x] add IDL tests
  * [x] preliminary implementation report / implementation status
     * tracked in #87
  * [x] CR exit criteria
     * PR #89

* [x] must specify the deadline for comments, which must be at least four weeks after publication, and should be longer for complex documents,
  * suggest six weeks

* [x] must show that the specification has received wide review,
  * [x] wide review started in Nov 2016
    * https://lists.w3.org/Archives/Public/public-review-announce/2016Nov/0008.html
  * [x] TAG review
    * https://github.com/w3ctag/spec-reviews/issues/145
  * [x] i18n review
    * https://github.com/w3c/i18n-activity/issues/274
  * [x] privacy review
    * https://lists.w3.org/Archives/Public/public-privacy/2017JanMar/0009.html
    * Feedback addressed in #83
  * [x] accessibility
    * https://lists.w3.org/Archives/Public/public-apa/2016Nov/0017.html
  * [x] security - no concerns or comments (to date)
    * https://lists.w3.org/Archives/Public/public-webappsec/2016Dec/0000.html
    * https://lists.w3.org/Archives/Public/public-web-security/2016Dec/0000.html
* [x] may identify features in the document as "at risk". These features may be removed before advancement to Proposed Recommendation without a requirement to publish a new Candidate Recommendation.
  * [x] address #41 to identify possible "at risk" features
    * see https://w3c.github.io/remote-playback/#sotd

[1]: https://w3c.github.io/remote-playback/
[2]: https://www.w3.org/2017/Process-20170301/#candidate-rec

**Comment by anssiko** [comment]
Ping @avayvod @mounirlamouri to check the availability to work on #41 and the [test suite update][1] blocking this CR publication.

[1]: https://github.com/w3c/web-platform-tests/tree/master/remote-playback#todo

**Comment by anssiko** [comment]
Gently nudging @avayvod @mounirlamouri.

Would it be helpful to have a topic-specific WG call to discuss the Remote Playback API plan to CR, associated requirements, things to do? Any specific areas where you'd especially welcome contributions from other WG participants? Let us know.

**Comment by markafoltz** [comment]
@anssiko It looks like the specification received TAG and privacy feedback so I checked those off.  Is i18n review expected to complete soon?

**Comment by anssiko** [comment]
@mfoltzgoogle, I pinged https://github.com/w3c/i18n-activity/issues/274. The i18n review has been in the "awaiting comment resolution" state since Feb 9.

**Comment by anssiko** [comment]
The i18n review has been completed, and one issue https://github.com/w3c/remote-playback/issues/70 was identified.

We should try to address this issue before going to CR. An informative note in the respective section  should address the issue.

**Comment by avayvod** [comment]
Do privacy reviews end up being summarized on GitHub like TAG or i18n? I'd like to respond to the comments we've got on public-privacy@w3c.org but not sure if this is the right way or we should wait until all the comments are summarized.

**Comment by anssiko** [comment]
@avayvod, the privacy folks use the mailing list, and not (yet) GitHub. Please respond on that list. This constitutes all of the privacy review feedback: https://lists.w3.org/Archives/Public/public-privacy/2017JanMar/0009.html

**Comment by avayvod** [comment]
Thanks @anssiko, I've sent a response [here](https://lists.w3.org/Archives/Public/public-privacy/2017AprJun/0025.html)!

**Comment by anssiko** [comment]
Current status: CR blockers are #41, #83, #87.

All have a proposal or a suggested resolution.

In addition to these blockers, we need to define the CR exit criteria and "at risk" features. @tidoust would you like to take a stab at them?

**Comment by tidoust** [comment]
> In addition to these blockers, we need to define the CR exit criteria and "at risk" features. @tidoust would you like to take a stab at them?

See proposal in PR #89

**Comment by anssiko** [comment]
Current status: CR blockers are #41, #87.

(Fixed since last week: #83, #89)

**Comment by anssiko** [comment]
Current status: the remaining CR blocker is #41 

@tidoust, could you take a look at the overall CR plan and see whether there are any other issues in your view that we should address prior to advancing to CR? If not, I'd like to issue a CfC to publish a Candidate Recommendation as soon as possible.

**Comment by mounirlamouri** [comment]
@anssiko sorry for coming late with this question but I thought we did not have two compatible implementations yet and that was a soft rule for CR given that we can't for beyond that stage without it. Is your plan to go to CR with one implementation and wait for another in order to go to PR/REC?

**Comment by tidoust** [comment]
@mounirlamouri I would personally still go to CR even if we only have one implementation in the pipe. 

The Director will most likely wonder about implementation plans when we ask to publish the CR, and it would be way better to have concrete plans to share for at least two implementations. However, that is indeed a soft rule. If we have but one implementation for now, then so be it, publication as a CR is also a way to tell the world that, apart from issues that may appear based on implementation feedback, the Working Group considers that the API is done and ready, which seems useful. It used to be a pain to publish updated CRs but that is no longer the case.

**Comment by anssiko** [comment]
@mounirlamouri, given the more agile CR publishing process, I'd prefer to go to CR early and publish an updated CR as needed, similarly to what we did with the Presentation API. I think we're about to reach consensus on the remaining blocker #41, please chime in there.

**Comment by anssiko** [comment]
#95 seems to address #41 for the purposes of the CR publication.

The process doc tells us CR may identify features in the document as "at risk". These features may be removed before advancement to Proposed Recommendation without a requirement to publish a new Candidate Recommendation.

Are we fine with the following boilerplate?

>No feature has been identified as being at risk.

Given the information we have re #41, that seems like the most accurate statement we can make at this time. Even if we end up dropping feature(s), we can still go to PR, we just have to publish another CR in between -- not a major hurdle anymore, a speed bump at most.

**Comment by anssiko** [comment]
Call for Consensus (CfC) to request publication of a Candidate Recommendation (CR) of the Remote Playback API:
https://lists.w3.org/Archives/Public/public-secondscreen/2017Aug/0033.html

**Comment by tidoust** [comment]
Current status:

- i18n issues #66 and #70 need to be addressed before transition to CR may happen. Done when PRs #99 and #100 are merged.
- We'll then need to get back to the i18n group and ask for final "green light", meaning closure of https://github.com/w3c/i18n-activity/issues/274
- I also noted in #101 a few notes with normative text which I think we should fix as well before transitioning. Done when PR #102 gets merged.

**Comment by anssiko** [comment]
All the last-minute CR blockers have been addressed and the i18n group has been informed. Thanks for your swift contributions.

@tidoust, please advance with the plan to request publication of a CR.

**Comment by tidoust** [comment]
Before the specification can transition to a Candidate Recommendation, the definition of the `disableRemotePlayback` content attribute should be made explicit (#105), and the Second Screen WG should request a review from the Web Platform Working Group (see [member-only discussion thread](https://lists.w3.org/Archives/Member/chairs/2017JulSep/0140.html)).

**Comment by anssiko** [comment]
#106 is the proposed fix to #105.

After landing, @tidoust to initiate request to review from the Web Platform WG.

**Comment by anssiko** [comment]
@tidoust, we should be now ready for the WP WG review.

**Comment by tidoust** [comment]
I [asked the Web Platform WG for review](https://lists.w3.org/Archives/Public/public-webapps/2017JulSep/0051.html), with a deadline for comments set to 10 October.

**Comment by anssiko** [comment]
The [Web Platform WG review period][1] has ended.

Issue https://github.com/w3c/remote-playback/issues/107 was opened during the review period which may or may not be in response to the review request. Nevertheless, the author of the issue @jyasskin approved the spec editor @mounirlamouri's suggestion. My assessment is the issue raised will not block the CR publication, thus I'd ask @tidoust to advance with the transition to a Candidate Recommendation at the earliest opportunity.

[1]: https://lists.w3.org/Archives/Public/public-webapps/2017JulSep/0051.html

**Comment by anssiko** [comment]
An update on the logistics of the CR publication:

I pushed a `cr` branch that needs to be rebased with `gh-pages` when PRs #108 and #110 are approved and merged. The [spec-generator snapshot][1] is used for publication, it passes [Pubrules][2] and  also [Link Checker][3] when the above-mentioned changes are baked into the `cr` branch. Earliest publication opportunity is 19 October 2017.

I believe we want to keep the WHATWG HTML references in the Editor's Draft, and as such, I suggest we keep 9980f4fb25adf0084544f27db874de8e5d72c6a1 in the `cr` branch for release purposes.

[1]: https://labs.w3.org/spec-generator/?type=respec&url=https://rawgit.com/w3c/remote-playback/cr/index.html?specStatus=CR;shortName=remote-playback;crEnd=2017-11-30;
[2]: https://www.w3.org/pubrules/
[3]: https://validator.w3.org/checklink

**Comment by anssiko** [comment]
PRs #108 and #110 have been merged into `gh-pages` and the `cr` branch rebased with `gh-pages` to pull in these changes.

@tidoust, can you please check that we're good to publish 19 October 2017?

The [spec-generator snapshot][1] passes [Pubrules][2] and [Link Checker][3]. You may want to address the Patent Policy warning by manually patching the snapshot, since the ReSpec patch https://github.com/w3c/respec/pull/1388 has not yet been merged. The [updated Patent Policy][4] only incorporates editorial updates to be consistent with the 2017 Process. 

[1]: https://labs.w3.org/spec-generator/?type=respec&url=https://rawgit.com/w3c/remote-playback/cr/index.html?specStatus=CR;shortName=remote-playback;crEnd=2017-11-30;
[2]: https://www.w3.org/pubrules/
[3]: https://validator.w3.org/checklink
[4]: https://www.w3.org/Consortium/Patent-Policy-20170801/

**Comment by tidoust** [comment]
The [Candidate Recommendation](https://www.w3.org/TR/2017/CR-remote-playback-20171019/) of the Remote Playback API has been published today (19 October 2017). Closing this as a result.

Well done, Second Screen WG!
